#!/usr/bin/env bash
set -euo pipefail

APP_NAME="gost"
BIN_PATH="/usr/local/bin/gost"
CONF_DIR="/etc/gost"
RULES_FILE="${CONF_DIR}/rules.conf"
ENV_FILE="${CONF_DIR}/gost.env"
SERVICE_FILE="/etc/systemd/system/gost.service"
CRON_FILE="/etc/cron.d/gost-restart"

RED="\033[31m"
GRN="\033[32m"
YEL="\033[33m"
BLU="\033[36m"
RST="\033[0m"

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo -e "${RED}请用 root 运行此脚本${RST}"
    exit 1
  fi
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo -e "${YEL}缺少依赖: $1，正在安装...${RST}"
    apt-get update -y >/dev/null 2>&1 || true
    apt-get install -y "$1" >/dev/null 2>&1 || {
      echo -e "${RED}安装依赖失败: $1${RST}"
      exit 1
    }
  }
}

prepare_env() {
  mkdir -p "${CONF_DIR}"
  touch "${RULES_FILE}"
  [[ -f "${ENV_FILE}" ]] || cat > "${ENV_FILE}" <<ENV_EOF
# Auto-generated by gost-manager.sh
GOST_ARGS=""
ENV_EOF
}

arch_map() {
  local arch
  arch="$(uname -m)"
  case "${arch}" in
    x86_64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    armv7l|armv7*) echo "armv7" ;;
    armv6l|armv6*) echo "armv6" ;;
    i386|i686) echo "386" ;;
    riscv64) echo "riscv64" ;;
    mips64*) echo "mips64" ;;
    mipsel*) echo "mipsle" ;;
    mips*) echo "mips" ;;
    *) echo "unsupported" ;;
  esac
}

install_gost_latest() {
  need_cmd curl
  need_cmd tar
  need_cmd awk
  need_cmd grep

  local os arch api version download_url tmp
  os="linux"
  arch="$(arch_map)"
  if [[ "${arch}" == "unsupported" ]]; then
    echo -e "${RED}不支持的架构: $(uname -m)${RST}"
    exit 1
  fi

  api="https://api.github.com/repos/go-gost/gost/releases"
  version="$(curl -fsSL "${api}" | awk -F'"' '/"tag_name":/ {print $4; exit}')"
  [[ -n "${version}" ]] || { echo -e "${RED}获取最新版本失败${RST}"; exit 1; }

  download_url="$(curl -fsSL "${api}/tags/${version}" \
    | awk -F'"' -v re=".*${os}.*${arch}.*" '/"browser_download_url":/ && $4 ~ re {print $4; exit}')"

  [[ -n "${download_url}" ]] || {
    echo -e "${RED}未找到对应平台安装包: ${os}/${arch}${RST}"
    exit 1
  }

  echo -e "${BLU}正在安装 gost ${version} (${os}/${arch})...${RST}"
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT

  curl -fsSL "${download_url}" | tar -xz -C "${tmp}"
  if [[ ! -f "${tmp}/gost" ]]; then
    local found
    found="$(find "${tmp}" -type f -name gost | head -n1 || true)"
    [[ -n "${found}" ]] || { echo -e "${RED}安装包内未找到 gost 二进制${RST}"; exit 1; }
    install -m 0755 "${found}" "${BIN_PATH}"
  else
    install -m 0755 "${tmp}/gost" "${BIN_PATH}"
  fi

  echo -e "${GRN}安装完成: $(${BIN_PATH} -V 2>/dev/null || ${BIN_PATH} -v 2>/dev/null || echo gost)${RST}"
}

create_service() {
  cat > "${SERVICE_FILE}" <<SERVICE_EOF
[Unit]
Description=GOST Tunnel Service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=${ENV_FILE}
ExecStart=${BIN_PATH} \$GOST_ARGS
Restart=always
RestartSec=2s
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
SERVICE_EOF

  systemctl daemon-reload
  systemctl enable gost >/dev/null 2>&1 || true
}

render_args_from_rules() {
  local args=""
  while IFS='|' read -r name l_arg f_arg extra; do
    [[ -z "${name:-}" ]] && continue
    [[ "${name}" =~ ^# ]] && continue
    args+=" -L='${l_arg}'"
    if [[ -n "${f_arg:-}" ]]; then
      args+=" -F='${f_arg}'"
    fi
    if [[ -n "${extra:-}" ]]; then
      args+=" ${extra}"
    fi
  done < "${RULES_FILE}"

  cat > "${ENV_FILE}" <<ENV_EOF
# Auto-generated by gost-manager.sh
GOST_ARGS=${args}
ENV_EOF
}

reload_service() {
  render_args_from_rules
  systemctl daemon-reload
  systemctl restart gost
}

list_rules() {
  echo -e "${BLU}当前规则：${RST}"
  if [[ ! -s "${RULES_FILE}" ]]; then
    echo "  (空)"
    return
  fi
  nl -ba "${RULES_FILE}" | sed 's/^/  /'
}

add_rule_custom() {
  local name l_arg f_arg extra
  echo -e "${BLU}添加自定义规则（建议最稳）${RST}"
  read -rp "规则名称(唯一): " name
  [[ -n "${name}" ]] || { echo -e "${RED}名称不能为空${RST}"; return; }

  if grep -q "^${name}|" "${RULES_FILE}" 2>/dev/null; then
    echo -e "${RED}规则名称已存在${RST}"
    return
  fi

  echo "示例:"
  echo "  -L: tcp://:10000/1.2.3.4:20000"
  echo "  -L: relay+ws://:443"
  echo "  -F: socks5://127.0.0.1:1080"
  read -rp "请输入 -L 参数值: " l_arg
  read -rp "请输入 -F 参数值(可空): " f_arg
  read -rp "额外参数(可空，如 --log.level info): " extra

  [[ -n "${l_arg}" ]] || { echo -e "${RED}-L 不能为空${RST}"; return; }
  echo "${name}|${l_arg}|${f_arg}|${extra}" >> "${RULES_FILE}"
  echo -e "${GRN}规则已添加${RST}"
}

add_rule_quick() {
  local name mode lport target user pass
  echo -e "${BLU}快速添加规则${RST}"
  echo "1) TCP 转发"
  echo "2) UDP 转发"
  echo "3) relay+tls"
  echo "4) relay+ws"
  echo "5) relay+wss"
  echo "6) 本机创建 socks5 代理"
  echo "7) 本机创建 http 代理"
  read -rp "选择模式 [1-7]: " mode

  read -rp "规则名称(唯一): " name
  [[ -n "${name}" ]] || { echo -e "${RED}名称不能为空${RST}"; return; }
  if grep -q "^${name}|" "${RULES_FILE}" 2>/dev/null; then
    echo -e "${RED}规则名称已存在${RST}"
    return
  fi

  case "${mode}" in
    1)
      read -rp "监听端口: " lport
      read -rp "目标地址(如 1.2.3.4:20000): " target
      echo "${name}|tcp://:${lport}/${target}||" >> "${RULES_FILE}"
      ;;
    2)
      read -rp "监听端口: " lport
      read -rp "目标地址(如 1.2.3.4:20000): " target
      echo "${name}|udp://:${lport}/${target}||" >> "${RULES_FILE}"
      ;;
    3)
      read -rp "监听端口: " lport
      read -rp "目标地址(如 1.2.3.4:20000): " target
      echo "${name}|relay+tls://:${lport}/${target}||" >> "${RULES_FILE}"
      ;;
    4)
      read -rp "监听端口: " lport
      read -rp "目标地址(如 1.2.3.4:20000): " target
      echo "${name}|relay+ws://:${lport}/${target}||" >> "${RULES_FILE}"
      ;;
    5)
      read -rp "监听端口: " lport
      read -rp "目标地址(如 1.2.3.4:20000): " target
      echo "${name}|relay+wss://:${lport}/${target}||" >> "${RULES_FILE}"
      ;;
    6)
      read -rp "监听端口: " lport
      read -rp "用户名(可空): " user
      read -rp "密码(可空): " pass
      if [[ -n "${user}" && -n "${pass}" ]]; then
        echo "${name}|socks5://${user}:${pass}@:${lport}||" >> "${RULES_FILE}"
      else
        echo "${name}|socks5://:${lport}||" >> "${RULES_FILE}"
      fi
      ;;
    7)
      read -rp "监听端口: " lport
      read -rp "用户名(可空): " user
      read -rp "密码(可空): " pass
      if [[ -n "${user}" && -n "${pass}" ]]; then
        echo "${name}|http://${user}:${pass}@:${lport}||" >> "${RULES_FILE}"
      else
        echo "${name}|http://:${lport}||" >> "${RULES_FILE}"
      fi
      ;;
    *)
      echo -e "${RED}无效选择${RST}"
      return
      ;;
  esac

  echo -e "${GRN}规则已添加${RST}"
}

delete_rule() {
  list_rules
  read -rp "输入要删除的规则名称: " name
  [[ -n "${name}" ]] || return
  if grep -q "^${name}|" "${RULES_FILE}"; then
    grep -v "^${name}|" "${RULES_FILE}" > "${RULES_FILE}.tmp"
    mv "${RULES_FILE}.tmp" "${RULES_FILE}"
    echo -e "${GRN}已删除: ${name}${RST}"
  else
    echo -e "${YEL}未找到规则: ${name}${RST}"
  fi
}

service_status() {
  systemctl status gost --no-pager || true
}

enable_cron_restart() {
  local spec
  echo "示例: 每天4点重启 -> 0 4 * * *"
  read -rp "请输入 crontab 时间表达式: " spec
  [[ -n "${spec}" ]] || { echo -e "${RED}不能为空${RST}"; return; }
  cat > "${CRON_FILE}" <<CRON_EOF
${spec} root systemctl restart gost >/dev/null 2>&1
CRON_EOF
  echo -e "${GRN}已设置定时重启: ${spec}${RST}"
}

disable_cron_restart() {
  rm -f "${CRON_FILE}"
  echo -e "${GRN}已取消定时重启${RST}"
}

uninstall_all() {
  read -rp "确认卸载 gost 及配置？[y/N]: " ans
  [[ "${ans}" =~ ^[Yy]$ ]] || return
  systemctl stop gost >/dev/null 2>&1 || true
  systemctl disable gost >/dev/null 2>&1 || true
  rm -f "${SERVICE_FILE}" "${BIN_PATH}" "${CRON_FILE}"
  rm -rf "${CONF_DIR}"
  systemctl daemon-reload
  echo -e "${GRN}已卸载完成${RST}"
}

show_menu() {
  echo
  echo -e "${BLU}==== GOST 一键管理 ====${RST}"
  echo "1) 安装/升级 gost"
  echo "2) 初始化 systemd 服务"
  echo "3) 查看规则"
  echo "4) 添加规则(快速模板)"
  echo "5) 添加规则(自定义)"
  echo "6) 删除规则"
  echo "7) 重载规则并重启服务"
  echo "8) 启动服务"
  echo "9) 停止服务"
  echo "10) 重启服务"
  echo "11) 查看服务状态"
  echo "12) 启用定时重启"
  echo "13) 关闭定时重启"
  echo "14) 卸载"
  echo "0) 退出"
}

main() {
  require_root
  prepare_env

  while true; do
    show_menu
    read -rp "请选择 [0-14]: " c
    case "${c}" in
      1) install_gost_latest ;;
      2) create_service; echo -e "${GRN}服务初始化完成${RST}" ;;
      3) list_rules ;;
      4) add_rule_quick ;;
      5) add_rule_custom ;;
      6) delete_rule ;;
      7) create_service; reload_service; echo -e "${GRN}已应用规则${RST}" ;;
      8) systemctl start gost ;;
      9) systemctl stop gost ;;
      10) systemctl restart gost ;;
      11) service_status ;;
      12) enable_cron_restart ;;
      13) disable_cron_restart ;;
      14) uninstall_all ;;
      0) exit 0 ;;
      *) echo -e "${YEL}无效输入${RST}" ;;
    esac
  done
}

main "$@"
